services:
  postgres:
    image: postgres:15-alpine
    container_name: tbot_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=tbot_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tbot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tbot_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  tbot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tbot_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/tbot_db
      DB_USER: postgres
      DB_PASSWORD: password
      # Порт приложения на контейнере
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - tbot_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  tbot_network:
    driver: bridge 